// <auto-generated />
using System;
using GamePlay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamePlay.Migrations
{
	[DbContext(typeof(GameDbContext))]
	[Migration("20250220153123_GamesTableEdit")]
	partial class GamesTableEdit
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "9.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("GamePlay.Models.GameRecord", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uuid");

					b.Property<DateTime>("Date")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("PlayerBlack")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("PlayerWhite")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("Result")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("Games");
				});
#pragma warning restore 612, 618
		}
	}
}
