name: Deploy GamePlay

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Publish to DockerHub
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Remove existing github source (if any)
        run: dotnet nuget remove source github || true

      - name: Authenticate with GitHub Packages
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/VuykoSheshych/index.json \
            --name github \
            --username VuykoSheshych \
            --password ${{ secrets.NUGET_DEPLOY_GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore GamePlayService.csproj

      - name: Publish project
        run: dotnet publish GamePlayService.csproj -c Release -o ./publish --no-restore

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/gameplay:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gameplay:latest

  deploy:
    needs: build-and-push
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status
          minikube update-context

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          sed -i 's|DOCKER_HUB_USERNAME_REPLACE|${{ secrets.DOCKER_HUB_USERNAME }}|g' k8s/gameplay.yaml
          sed -i 's|GAMEPLAY_DB_CONNECTION_REPLACE|${{ secrets.GAMEPLAY_DB_CONNECTION}}|g' k8s/gameplay.yaml
          sed -i 's|GAMEPLAY_DB_USER_REPLACE|${{ secrets.GAMEPLAY_DB_USER }}|g' k8s/gameplay-db.yaml
          sed -i 's|GAMEPLAY_DB_PASSWORD_REPLACE|${{ secrets.GAMEPLAY_DB_PASSWORD }}|g' k8s/gameplay-db.yaml
          sed -i 's|GAMEPLAY_DB_REPLACE|${{ secrets.GAMEPLAY_DB }}|g' k8s/gameplay-db.yaml
          kubectl apply -f k8s/
          kubectl set image deployment/gameplay gameplay=${{ secrets.DOCKER_HUB_USERNAME }}/gameplay:latest
          kubectl rollout restart deployment/gameplay
